import type { App } from "obsidian";
import type { ChangeProposal } from "../changeset/ChangeProposal";
import type { AuditLog } from "../safety/AuditLog";

/**
 * Writes a structured markdown run report to "Gardener/Reports/YYYY-MM-DD.md".
 * Called at the end of runPipeline() when settings.saveRunReport is true.
 */
export async function generateRunReport(
  app: App,
  proposals: ChangeProposal[],
  autoApplied: number,
  durationMs: number,
  audit?: AuditLog
): Promise<void> {
  const now = new Date();
  const dateStr = now.toISOString().slice(0, 10);
  const timeStr = now.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" });
  const folderPath = "Gardener/Reports";

  // Ensure folder exists
  try {
    await app.vault.adapter.mkdir(folderPath);
  } catch {
    // already exists
  }
  try {
    await app.vault.adapter.mkdir("Gardener");
  } catch {
    // already exists
  }

  // Per-task breakdown
  const byTask = new Map<string, ChangeProposal[]>();
  for (const p of proposals) {
    if (!byTask.has(p.taskId)) byTask.set(p.taskId, []);
    byTask.get(p.taskId)!.push(p);
  }

  const taskRows = [...byTask.entries()]
    .map(([id, ps]) => `| ${id} | ${ps.length} |`)
    .join("\n");

  const proposalList = proposals
    .map(
      (p) =>
        `- **${p.title}** — ${p.targetPath}${p.secondaryPath ? ` ↔ ${p.secondaryPath}` : ""}`
    )
    .join("\n");

  const report = `# Gardener Run Report — ${dateStr}

> Generated at ${timeStr} · ${Math.round(durationMs / 1000)}s · ${proposals.length} proposals · ${autoApplied} auto-applied

## Summary

| Task | Findings |
|------|----------|
${taskRows || "| (none) | 0 |"}

**Total proposals staged for review:** ${proposals.length - autoApplied}
**Auto-applied (above trust threshold):** ${autoApplied}

## Proposals

${proposalList || "_No proposals this run — vault looks healthy!_"}

---
*Report generated by [Gardener](obsidian://open-plugin?id=obsidian-gardener)*
`;

  const reportPath = `${folderPath}/${dateStr}.md`;
  const existing = app.vault.getAbstractFileByPath(reportPath);
  if (existing) {
    await app.vault.modify(existing as Parameters<typeof app.vault.modify>[0], report);
  } else {
    await app.vault.create(reportPath, report);
  }
  await audit?.writeInternal(reportPath, `run report; proposals=${proposals.length}; autoApplied=${autoApplied}`, "run-report");
}
