import type { App, TFile } from "obsidian";
import type { Task, Finding } from "./Task";
import type { VaultIndex } from "../index/VaultIndex";
import type { GardenerSchema } from "../schema/GardenerSchema";
import type { LLMProvider } from "../llm/LLMProvider";
import type { GardenerSettings, AgentIntegration } from "../main";
import { agentSchemaFilePath, buildAgentSchema } from "../main";
import { newProposalId, buildDiff } from "../changeset/ChangeProposal";

export class WikiAgentSchemaTask implements Task {
  readonly id = "wiki-agent-schema";

  constructor(
    private app: App,
    private settings: GardenerSettings,
  ) {}

  async run(_index: VaultIndex, _schema: GardenerSchema, _llm: LLMProvider): Promise<Finding[]> {
    const agent = this.settings.agentIntegration;
    if (!agent || agent === "none") return [];
    if (!this.settings.wikiWriterEnabled) return [];

    const filePath = agentSchemaFilePath(agent as AgentIntegration);
    if (!filePath) return [];

    const after = buildAgentSchema(agent as AgentIntegration, this.settings);
    const existingFile = this.app.vault.getAbstractFileByPath(filePath) as TFile | null;
    const before = existingFile ? (await this.app.vault.cachedRead(existingFile).catch(() => "")) : "";

    // Only propose if content meaningfully changed (beyond the date line)
    const stripDate = (s: string) => s.replace(/Auto-generated by Gardener on \d{4}-\d{2}-\d{2}/, "");
    if (stripDate(before) === stripDate(after)) return [];

    return [{
      taskId: this.id,
      confidence: 0.95,
      proposal: {
        id: newProposalId(),
        taskId: this.id,
        type: "add-content",
        operation: "replace-file",
        targetPath: filePath,
        title: `Update ${filePath} (agent wiki schema)`,
        rationale: `Wiki Writer is enabled with ${agent} integration. Keeping ${filePath} in sync with current Gardener settings.`,
        diff: buildDiff(before, after),
        before,
        after,
        confidence: 0.95,
        createdAt: Date.now(),
      },
    }];
  }
}
